services:
  jenkins:
    image: jenkins-terraform:latest
    container_name: jenkins
    build: .
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./init-scripts:/usr/share/jenkins/ref/init.groovy.d:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - PLUGINS_FORCE_UPGRADE=true
    networks:
      jenkins_net:
        ipv4_address: 172.25.0.10
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "github.com:140.82.121.4"  # Добавляем github.com в hosts
      - "ya.ru:77.88.55.242"       # Пример для ya.ru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jenkins_home:
    name: jenkins-data

networks:
  jenkins_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
